train_config:
  expdir: /lustre/fsw/portfolios/adlr/users/sreyang/flamingo_v2/af2_exp_qwen3b_rotary_all_layers-7b-fixed
  run_name: run_demo_pretraining_bf16_xattnevery1_msclapcap_win7_ovlp5.25_single16win-4node-qwen3b-rotary-3b-fixed
  delete_previous_checkpoint: true 
  batch_size: 4
  gradient_accumulation_steps: 2  # 4 nodes
  seed: 42
  learning_rate: 0.0001
  lr_scheduler: constant
  loss_multiplier: 1.0
  warmup_steps: 1875
  weight_decay: 0.1
  precision: amp_bf16  # ["amp_bf16", "amp_bfloat16", "bf16", "fp16", "fp32"]
  gradient_checkpointing: False 
  num_epochs: 200  # num_epochs * dataset_blending_global_weight = 1
  offline: false
  freeze_lm_embeddings: false
  logging_steps: 10
  dist_backend: nccl
  dist_url: env:// # tcp://localhost:7000
  no_set_device_rank: false 
  fsdp: true 
  fsdp_use_orig_params: false  # Passed into the FSDP constructor. Enables param_groups and gradient masking for weight_decay. Does not work with OPT.
  fsdp_sharding_strategy: full  # full, hybrid
  horovod: false

data_config:
  dataset_blending_global_weight: 0.005

  dataset_blending_config:
  
    # Audio QA
    OpenAQA-AQA/train:
      weight: 1.0

    AudioSet-Temporal-Speech-Audio-QA/train:
      weight: 2.0

    CompA-R-AQA/train:
      weight: 2.0

    # Audio Captioning 

    BBCSoundEffects-AudioDescription/train: 
      weight: 5.0

    CLAP_freesound-AudioCaptioning/train: 
      weight: 1.0

    SoundDescs-AudioDescription/train:
      weight: 1.0

    WavCaps-AudioSet_SL-AudioCaptioning/train: 
      weight: 1.0

    WavCaps-BBC_Sound_Effects-AudioCaptioning/train: 
      weight: 2.0

    WavCaps-FreeSound-AudioCaptioning/train: 
      weight: 2.0

    WavCaps-SoundBible-AudioCaptioning/train: 
      weight: 5.0

    Ego-10-AudioCaptioning/train: 
      weight: 2.0

    Ego-30-AudioCaptioning/train: 
      weight: 2.0
    
    # Audio Classification

    AudioSetFullwoAudioMusicCaps-EventClassification/train:
      weight: 1.0

    AudioSet-EventClassification/train: 
      weight: 5.0

    Clotho-AQA-EventClassification/train: 
      weight: 5.0

    WavText5K-Tagging/train: 
      weight: 3.0

    # Speech Emotion Classification

    MSP-PODCAST-Publish-1.9-EmotionClassification/train:
      weight: 3.0

    MELD-EmotionClassification/train:
      weight: 3.0

    MELD-SentimentClassification/train:
      weight: 3.0
    
    # Music QA
    
    Music-AVQA-AVQA_All/train:
      weight: 3.0
    
    MU-LLAMA-AQA/train:
      weight: 3.0
    
    # Music Captioning

    LP-MusicCaps-MSD-AudioCaptioning/train:
      weight: 1.0

    # Music Understanding 

    NSynth-MIR/train:
      weight: 1.0
    
    mtg-jamendo-MusicTagging/train:
      weight: 1.0
    
  dataset_file_root: /lustre/fsw/portfolios/adlr/users/sreyang/final_qa/foundational_data
  data_root: /lustre/fsw/portfolios/adlr/users/zkong/datasets
  dataset_blending_output: /lustre/fsw/portfolios/adlr/users/sreyang/flamingo_v2/af2_exp_qwen3b_rotary_all_layers-7b-fixed/dataset_blending.json
  max_tokens: 512
  num_workers: 4

  valid_dataset_config: 
    CLAP_freesound-AudioCaptioning/test: true 
    SoundDescs-AudioDescription/test: true
    Clotho-AQA-EventClassification/test: true

    MSP-PODCAST-Publish-1.9-EmotionClassification/test: true 
    MELD-EmotionClassification/test: true
    MELD-SentimentClassification/test: true

    MU-LLAMA-AQA/test: true 
    LP-MusicCaps-MSD-AudioCaptioning/val: true 
    NSynth-MIR/test: true
    mtg-jamendo-MusicTagging/val: true

clap_config:  
  method: nvclap-large
  audio_embed_dim: 2048
  checkpoint: /lustre/fsw/portfolios/adlr/users/sreyang/datasets/clap_datasets/clap_ckpts_5/15/ck_sim/checkpoints/epoch_15.pt

  window_length: 10.0  # seconds
  window_overlap: 0.0  # seconds
  max_num_window: 3  # 5 minutes
  max_num_fewshot: 1  # number of fewshot samples (including the final one)

whisper_config:  
  method: whisper-large-v3
  path: openai/whisper-large-v3
  audio_embed_dim: 1280
  sampling_rate: 16000

  window_length: 30.0  # seconds
  window_overlap: 0.0  # seconds
  max_num_window: 1  # 5 minutes
  max_num_fewshot: 1  # number of fewshot samples (including the final one)
  finetune: true

mert_config:  
  method: mert-v1
  path: m-a-p/MERT-v1-330M
  audio_embed_dim: 1024
  sampling_rate: 24000

  window_length: 10.0  # seconds
  window_overlap: 0.0  # seconds
  max_num_window: 1  # 5 minutes
  max_num_fewshot: 1  # number of fewshot samples (including the final one)

model_config:
  cache_dir: /lustre/fsw/portfolios/adlr/users/sreyang/.cache

  lang_encoder_path: Qwen/Qwen2.5-3B
  tokenizer_path: Qwen/Qwen2.5-3B
  cross_attn_every_n_layers: 1
  audio_transformer_kwargs: {
    n_head: 8,
    n_layers: 3,
    d_inner: 2048,
    max_num_media: 128,  # must be >= max_num_window * num_fewshot_samples (4)
    max_window_per_audio: 1,  # must = max_num_window
    common_encoder_embed_dim: 1024
  }